#!/bin/sh

# insert your sonarQube key after login
echo Starting SonarQube
./gradlew sonarqube   -Dsonar.host.url=http://localhost:9000   -Dsonar.login=d3c1868445eaf0f47204028409337e7920073618
echo Finished SonarQube
