#!/bin/sh

# insert your sonarQube key after login
echo Starting SonarQube

value=`cat scripts/sonarqubeToken`
./gradlew sonarqube -Dsonar.host.url=http://localhost:9000   -Dsonar.login=${value} &

echo Finished SonarQube
